### PR TITLE
Player#setExp and Player#getExp now use the correct scale. Fixes #83 

### LINKED ISSUE #83: Player#setExp uses wrong scale
Bukkit uses a scale from 0.0 to 1.0 for the exp bar, while Nukkit uses one from 0 to 10.
Right now, calling Player.setExp(1) sets the bar to only 1/10th filled, while it should give a full bar .

### PR DESCRIPTION
**Pull request by RaynLegends**
Fixed by directly applying the percent of the bar to be filled instead of using Nukkit's methods which use a scale that depends on the level of the player.

### CODE REVIEW

**Comment by RaynLegends** [comment]
Added a commit:
Implemented some methods in PokkitLiveInventory and PokkitPlayer

File: src/main/java/nl/rutgerkok/pokkit/world/PokkitWorld.java [hunk 1]
```diff
@@ -358,8 +358,15 @@ public boolean getKeepSpawnInMemory() {
 
 	@Override
 	public List<LivingEntity> getLivingEntities() {
-		throw Pokkit.unsupported();
-
+		List<LivingEntity> livingEntities = new ArrayList<LivingEntity>();
+		
+		for (Entity entity : getEntities()) {
```
Comment (rutgerkok) [inline src/main/java/nl/rutgerkok/pokkit/world/PokkitWorld.java]: I think this method uses more resources than necessary. This method calls getEntities, which allocates a List and Entity wrappers for all entities. Then this method creates another list, and throws many of the previously allocated entities out.

It think something like this would be better:

```javascript
List<LivingEntity> livingEntities = new ArrayList<>();
for (cn.nukkit.entity.Entity entity : nukkit.getEntities()) {
	if (Nukkit reports entity is a living entity) {
 		livingEntities.add((LivingEntity) PokkitEntity.toBukkit(entity));
	}
}
return livingEntities;
```

**Comment by rutgerkok** [comment]
Looks nice! I have only one comment, see above.

If you want, I can give you access to this repo. In that way, there is no need to open a pull request for every change.

**Comment by RaynLegends** [comment]
That would be nice!

**Comment by rutgerkok** [comment]
Merged, thanks! I have sent you an invite.
